name: ROS 2 CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # ROS 2 のインストール準備
      - name: Set up ROS 2
        run: |
          # ROS 2 の公開鍵を追加
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          
          # ROS 1 用リポジトリの設定
          sudo bash -c "echo 'deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main' > /etc/apt/sources.list.d/ros-latest.list"
          
          # ROS 2 用リポジトリの設定
          sudo bash -c "echo 'deb http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main' > /etc/apt/sources.list.d/ros2-latest.list"
          
          # パッケージリストの更新
          sudo apt update -y

      # 必要な依存関係のインストール
      - name: Install ROS 2 Dependencies
        run: |
          # 一時的にキャッシュをクリアし、パッケージリストを更新
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt update
          
          # 必要なパッケージのインストール
          sudo apt install -y \
            python3-colcon-common-extensions \
            python3-vcstool \
            ros-foxy-desktop

      # インストール後の設定が正常であることを確認
      - name: Check ROS 2 Installation
        run: |
          # ROS 2 のインストール確認
          source /opt/ros/foxy/setup.bash
          ros2 --help
          
      # ワークスペースのビルド
      - name: Build workspace with colcon
        run: |
          # 作業ディレクトリに移動し、ビルド
          mkdir -p ~/ros2_ws/src
          cd ~/ros2_ws
          colcon build --symlink-install
          
      # 動作確認（お好みで）
      - name: Run ROS 2 example node
        run: |
          # ROS 2 の環境変数をソースしてからノードを実行
          source /opt/ros/foxy/setup.bash
          source ~/ros2_ws/install/setup.bash
          ros2 run demo_nodes_cpp talker

